#!/bin/sh
### BEGIN INIT INFO
# Provides:          firewall
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO
case $1 in
 start)
  echo "miscelanea" >> /var/log/firewall
  echo "Configurando Router" >> /var/log/firewall
  echo 1 > /proc/sys/net/ipv4/ip_forward
  modprobe ip_conntrack_ftp
  modprobe ip_nat_ftp
  modprobe ip_conntrack_irc
 # configuracion basica de routing
 iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
 # entradas especificas de redes
 #iptables -A FORWARD -s 172.26.6.0/24 -d 172.26.0.0/24 -j DROP
 #iptables -A FORWARD -s 172.26.11.0/24 -d 172.26.6.0/24 -j DROP
 #iptables -A FORWARD -s 172.26.11.0/24 -d 172.26.0.0/24 -j DROP
 #iptables -A FORWARD -s 172.26.6.0/24 -d 172.26.0.0/24 -j ACCEPT
 #iptables -A FORWARD -s 172.26.0.0/24 -d 172.26.6.0/24 -j ACCEPT
 #iptables -A FORWARD -s 172.26.11.0/24 -d 172.26.6.0/24 -j ACCEPT
 
 # opciones de salida por redes
 #iptables -t nat -A POSTROUTING -s 172.26.6.0/24 -o eth0 -j MASQUERADE
 #iptables -t nat -A POSTROUTING -s 172.26.11.0/24 -o eth0 -j MASQUERADE
 #iptables -t nat -A POSTROUTING -s 172.26.0.0/24 -o eth0 -j MASQUERADE
 
 # puerto de entrada redirigido 
 #iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -s my.dynamic.domain -j DNAT --to 172.26.0.100:80

# Configuracion del bridge, sin spanning tree
#  ifconfig eth1 up
#  ifconfig eth2 up
#  brctl addbr br0
#  brctl addif br0 eth2
#  brctl addif br0 eth1

#  /usr/local/sbin/iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
 ;;
 stop)
  echo "Borrando reglas de iptables" >> /var/log/firewall
  iptables -t nat -F
 ;;
esac
